---
loki_targets:
  - name: loki1
    host: loki
    port: 3100
    username: admin
    password: admin
    auth_enabled: false
    protocol: http
    tenant: tenant1
    source: loki_data_generator
    # Common labels for all streams
    labels:
      environment: development
    streams:
      - name: stream1
        # Labels for this stream
        labels:
          device: device1
        pause_between_messages: 0.1
        sleep_between_cycles: 1
        messages:
          - template: "{timestamp} Sample INFO message with random string {random_string} and random number {random_number}"
            level: INFO
            probability: 0.1
          - template: "{timestamp} Sample ERROR message with random string {random_string} and random number {random_number}"
            level: ERROR
            probability: 0.01
